spring:
  datasource:
    url: jdbc:mysql://localhost:3306/viagemslz?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: "Flamengo20@"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  thymeleaf:
    enabled: true
    templates:
      root: classpath:/templates/